version: "3"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/var/www
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lim/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db-data:
    driver: local